services:
  pgvector:
    image: pgvector/pgvector:0.8.1-pg18
    container_name: pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  pgvector_data:
