"""Add rating

Revision ID: 0e89cda845c7
Revises: 20251109_add_user_department
Create Date: 2025-11-16 08:50:46.032661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e89cda845c7'
down_revision: Union[str, None] = '20251109_add_user_department'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('collection_1024_1_vector_idx', table_name='collection_1024_1', postgresql_using='hnsw')
    op.drop_table('collection_1024_1')
    op.drop_table('collection_1024_56')
    op.drop_table('collection_1024_53')
    op.drop_table('collection_1024_52')
    op.add_column('assets', sa.Column('asset_visibility', sa.String(), nullable=False))
    op.add_column('assets', sa.Column('asset_department', sa.String(), nullable=True))
    op.create_index('ix_asset_department', 'assets', ['asset_department'], unique=False)
    op.create_index('ix_asset_visibility', 'assets', ['asset_visibility'], unique=False)
    op.drop_column('chat_conversations', 'conversation_tags')
    op.add_column('chat_history', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('chat_history', sa.Column('is_helpful', sa.Boolean(), nullable=True))
    op.add_column('chat_history', sa.Column('fallback_used', sa.Boolean(), nullable=True))
    op.add_column('chat_history', sa.Column('retrieved_chunks', sa.Integer(), nullable=True))
    op.add_column('chat_history', sa.Column('retrieved_doc_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chat_history', sa.Column('retrieved_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'retrieved_asset_ids')
    op.drop_column('chat_history', 'retrieved_doc_types')
    op.drop_column('chat_history', 'retrieved_chunks')
    op.drop_column('chat_history', 'fallback_used')
    op.drop_column('chat_history', 'is_helpful')
    op.drop_column('chat_history', 'rating')
    op.add_column('chat_conversations', sa.Column('conversation_tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('ix_asset_visibility', table_name='assets')
    op.drop_index('ix_asset_department', table_name='assets')
    op.drop_column('assets', 'asset_department')
    op.drop_column('assets', 'asset_visibility')
    op.create_table('collection_1024_52',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_1024_52_chunk_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='collection_1024_52_pkey')
    )
    op.create_table('collection_1024_53',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_1024_53_chunk_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='collection_1024_53_pkey')
    )
    op.create_table('collection_1024_56',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_1024_56_chunk_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='collection_1024_56_pkey')
    )
    op.create_table('collection_1024_1',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_1024_1_chunk_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='collection_1024_1_pkey')
    )
    op.create_index('collection_1024_1_vector_idx', 'collection_1024_1', ['vector'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
