"""chat conversations, doc types, stats columns

Revision ID: 517b29f90ead
Revises: e0f5c44b337a
Create Date: 2025-11-06 15:18:00.136314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '517b29f90ead'
down_revision: Union[str, None] = 'e0f5c44b337a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    op.add_column('chat_history', sa.Column('model_key', sa.String(), nullable=True))
    op.add_column('chat_history', sa.Column('doc_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'doc_types')
    op.drop_column('chat_history', 'model_key')
    op.drop_column('chat_history', 'response_time_ms')
    # ### end Alembic commands ###
