"""resources column

Revision ID: 6ea278d7f170
Revises: 3b1073f9ff0a
Create Date: 2025-11-23 12:11:51.483615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ea278d7f170'
down_revision: Union[str, None] = '3b1073f9ff0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('collection_2560_52_fts_idx', table_name='collection_2560_52', postgresql_using='gin')
    op.drop_table('collection_2560_52')
    op.add_column('chat_history', sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'resources')
    op.create_table('collection_2560_52',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, COALESCE(text, ''::text))", persisted=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_2560_52_chunk_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='collection_2560_52_pkey')
    )
    op.create_index('collection_2560_52_fts_idx', 'collection_2560_52', ['fts'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
