"""add users and chat_history tables

Revision ID: 764da34807fa
Revises: 7f0d537442af
Create Date: 2025-11-04 07:08:24.052972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764da34807fa'
down_revision: Union[str, None] = '7f0d537442af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_is_admin', 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.add_column('assets', sa.Column('asset_user_id', sa.Integer(), nullable=False))
    op.add_column('assets', sa.Column('asset_is_private', sa.Boolean(), nullable=False))
    op.create_index('ix_asset_is_private', 'assets', ['asset_is_private'], unique=False)
    op.create_index('ix_asset_user_id', 'assets', ['asset_user_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'users', ['asset_user_id'], ['id'])
    op.add_column('projects', sa.Column('project_user_id', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('project_is_private', sa.Boolean(), nullable=False))
    op.create_index('ix_project_is_private', 'projects', ['project_is_private'], unique=False)
    op.create_index('ix_project_user_id', 'projects', ['project_user_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['project_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index('ix_project_user_id', table_name='projects')
    op.drop_index('ix_project_is_private', table_name='projects')
    op.drop_column('projects', 'project_is_private')
    op.drop_column('projects', 'project_user_id')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index('ix_asset_user_id', table_name='assets')
    op.drop_index('ix_asset_is_private', table_name='assets')
    op.drop_column('assets', 'asset_is_private')
    op.drop_column('assets', 'asset_user_id')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_is_admin', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
