"""chat conversations and document types

Revision ID: e0f5c44b337a
Revises: 764da34807fa
Create Date: 2025-11-06 05:53:46.718982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f5c44b337a'
down_revision: Union[str, None] = '764da34807fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('ix_chat_conversations_user_title', 'chat_conversations', ['conversation_user_id', 'conversation_title'], unique=False)
    op.add_column('assets', sa.Column('asset_document_type', sa.String(), nullable=False))
    op.create_index('ix_asset_document_type', 'assets', ['asset_document_type'], unique=False)
    op.add_column('chat_history', sa.Column('conversation_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chat_history_conversation_id'), 'chat_history', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'chat_history', 'chat_conversations', ['conversation_id'], ['conversation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_index(op.f('ix_chat_history_conversation_id'), table_name='chat_history')
    op.drop_column('chat_history', 'conversation_id')
    op.drop_index('ix_asset_document_type', table_name='assets')
    op.drop_column('assets', 'asset_document_type')
    op.drop_index('ix_chat_conversations_user_title', table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
