from enum import Enum

class ResponseSignal(Enum):

    FILE_VALIDATED_SUCCESS = "file_validate_successfully"
    FILE_TYPE_NOT_SUPPORTED = "file_type_not_supported"
    FILE_SIZE_EXCEEDED = "file_size_exceeded"
    FILE_UPLOAD_SUCCESS = "file_upload_success"
    FILE_UPLOAD_FAILED = "file_upload_failed"
    FILE_LIST_SUCCESS = "file_list_success"
    FILE_DELETE_SUCCESS = "file_delete_success"
    PROCESSING_SUCCESS = "processing_success"
    PROCESSING_FAILED = "processing_failed"
    NO_FILES_ERROR = "not_found_files"
    FILE_ID_ERROR = "no_file_found_with_this_id"
    PROJECT_NOT_FOUND_ERROR = "project_not_found"
    INSERT_INTO_VECTORDB_ERROR = "insert_into_vectordb_error"
    INSERT_INTO_VECTORDB_SUCCESS = "insert_into_vectordb_success"
    VECTORDB_COLLECTION_RETRIEVED = "vectordb_collection_retrieved"
    VECTORDB_SEARCH_ERROR = "vectordb_search_error"
    VECTORDB_SEARCH_SUCCESS = "vectordb_search_success"
    RAG_ANSWER_ERROR = "rag_answer_error"
    RAG_ANSWER_SUCCESS = "rag_answer_success"
    SUMMARY_GENERATION_ERROR = "summary_generation_error"
    SUMMARY_GENERATION_SUCCESS = "summary_generation_success"
    RAG_ANSWER_STREAM_START = "rag_answer_stream_start"
    RAG_ANSWER_STREAM_DELTA = "rag_answer_stream_delta"
    SUMMARY_STREAM_START = "summary_stream_start"
    SUMMARY_STREAM_DELTA = "summary_stream_delta"
    USER_STATS_SUCCESS = "user_stats_success"
    ADMIN_STATS_SUCCESS = "admin_stats_success"
    CONVERSATIONS_FETCH_SUCCESS = "conversations_fetch_success"
    CONVERSATION_HISTORY_SUCCESS = "conversation_history_success"
    USER_NOT_FOUND_ERROR = "user_not_found"
    ACCESS_FORBIDDEN_ERROR = "access_forbidden"
    UNAUTHORIZED_ERROR = "unauthorized_request"
    USER_CREATED_SUCCESS = "user_created_success"
    USER_ALREADY_EXISTS = "user_already_exists"
    ADMIN_CREATED_SUCCESS = "admin_created_success"
    INVALID_CREDENTIALS_ERROR = "invalid_credentials"
